name: SonarQube Check
on:
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

  pull_request:
    branches:
      - 'main'
      - 'release/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  call-sonarcloud-check:
    uses: bellumai/ios-github-workflows/.github/workflows/spm-sonarqube.yml@v1
    secrets: inherit
